/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.trimart.csvconverter

import java.io.File
import java.nio.file.FileSystems

class App {

    private val separator: String = FileSystems.getDefault().separator

    fun process(baseFileLocation: String, savePathLocation: String) {
        val saveLocation = if (savePathLocation.contains("~")) {
            savePathLocation.replace("~", System.getProperty("user.home"))
        } else {
            savePathLocation
        }
        val file = File(baseFileLocation)
        if (file.exists()) {
            val cncSpecs = mutableListOf<CncSpec>()
            val bufferedReader = file.inputStream().bufferedReader(Charsets.UTF_16)
            bufferedReader.forEachLine {
                if (!it.startsWith("^")) {
                    val items = it.split(",")
                    cncSpecs.add(
                        CncSpec(
                        fileName = items[0],
                        sheetNumber = items[1],
                        width = items[2].toFloat(),
                        length = items[3].toFloat(),
                        thickness = items[4].toFloat(),
                        woodType = items[5],
                        folderName = file.parentFile.name
                     )
                    )
                }
            }
            File("$saveLocation${separator}${file.name}_Converted.csv").writeText(cncSpecs.joinToString(separator = "\n") {
                it.convertToString()
            })
        } else {
            error("Input File does not exist. $baseFileLocation")
        }
    }

}

fun main(args: Array<String>) {
    if (args.size != 2) {
        error("Missing required parameters. ArgsSize=${args.size} Args=${args.joinToString(",")}")
    }

    val app = App()

    app.process(args[0], args[1])
}
