/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.trimart.csvconverter

import io.mockk.junit5.MockKExtension
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.extension.ExtendWith
import org.junit.jupiter.api.extension.Extensions
import kotlin.test.Test
import kotlin.test.assertNotNull

@Extensions(
    ExtendWith(MockKExtension::class)
)
class AppTest {

    private lateinit var app: App

    @BeforeEach
    fun setup() {
        app = App()
    }

    @Test
    fun happyPath() {
        app.process("/Users/bradykurtz/Projects/trimArt/csvConverter/src/test/resources/4_18 Benches/CncRun492.csv", "~/Downloads")
        println("Does it Work?")
    }
}
